// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

package autoscalingiface_test

import (
	"testing"

	"bosun.org/_third_party/github.com/aws/aws-sdk-go/service/autoscaling"
	"bosun.org/_third_party/github.com/aws/aws-sdk-go/service/autoscaling/autoscalingiface"
	"bosun.org/_third_party/github.com/stretchr/testify/assert"
)

func TestInterface(t *testing.T) {
	assert.Implements(t, (*autoscalingiface.AutoScalingAPI)(nil), autoscaling.New(nil))
}
